### ISSUE TITLE
Ionide FAKE creates new output window on each use

### ISSUE THREAD

**Issue by NatElkins** [ionide/ionide-vscode-fake#10]
I'm using the Ionide FAKE build integration.  On each use, a new FAKE output window is created (see below).

![fake_issue](https://cloud.githubusercontent.com/assets/1795462/15545544/adc58e70-226a-11e6-8ebf-16bbebc8105c.png)

Is this a feature?  I would expect that subsequent usages would simply log the text to the existing output window.

I am using VS Code 1.1.1 and Ionide FAKE 1.0.11.

Thanks!

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.1.0`
