### ISSUE TITLE
FAKE Build without running build.cmd

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fake#12]
For doing builds of custom commands - e.g. build project / solution, I don't always necessarily want to run build.cmd (which does paket restore, which takes some seconds). There should be some way to call the fake script directly (or redirect to a different build.cmd which doesn't call Paket etc.)

**Comment by Krzysztof-Cieslak** [comment]
You can provide different command to run in `.ionide` file as described in https://github.com/ionide/ionide-vscode-fake#configuration
