### ISSUE TITLE
Targets that contain minus char not shown in autocomplete

### ISSUE THREAD

**Issue by coolya** [ionide/ionide-vscode-fake#8]
I have the following target:

```
Target "clean" (fun _ ->
    CleanDir buildDir
)

Target "arduino-collector" (fun _ ->
    !! "arduino-collector/arduino-collector.fsproj"
        |> MSBuildRelease (buildDir + "/arduino-collector") "Build"
        |> Log "arduino-collector-output: "
)

Target "persistence" (fun _ ->
    !! "persistence/persistence.fsproj"
        |> MSBuildRelease (buildDir + "/persistence") "Build"
        |> Log "persistence-outpur: "
)

Target "all" (fun _ -> trace "build all")
Target "rebuild" (fun _ -> trace "full rebuild")

"arduino-collector"
    ==> "all"

"persistence"
    ==> "all"
```
When I select `FAKE: Build` from the command menu the `arduino-collector` is not shown:
<img width="804" alt="screen shot 2016-02-02 at 10 07 32" src="https://cloud.githubusercontent.com/assets/407216/12744507/ff63f4b2-c994-11e5-9951-f13e56f0da20.png">

If I change the name to `arduinocollector` it shows up:
<img width="767" alt="screen shot 2016-02-02 at 10 07 53" src="https://cloud.githubusercontent.com/assets/407216/12744531/1598e2ba-c995-11e5-9ff2-f40d6543a8f0.png">

**Comment by Krzysztof-Cieslak** [comment]
Nice catch, it's probably problem with regex we are using to find defined targets.
